[env:ch552]
platform = file://pio-platform
board = ch552
; CH55xDuino 0.0.25: CH552 Board, USER CODE w/ 148B USB RAM,
; 24 MHz internal (5V), USB upload, P3.6 (D+) pull-up.
board_build.f_cpu = 24000000
board_build.usb_ram = 148
board_build.physical_variant = 0
board_upload.bootcfg = 3
upload_protocol = usb
extra_scripts = pio-platform/targets.py
